---
attendee-types:
  - name: "Speaker"
    color: "211, 165, 255"
    ticket-titles:
      - "Speakers"
  - name: "Sponsor"
    color: "161, 216, 253"
    position: "100,100"
    ticket-titles:
      - "Sponsors"
  - name: "Organizer"
    color: "255, 109, 10"
    ticket-titles:
      - "Organizers"
  - name: "Volunteer"
    color: "235, 95, 95"
    ticket-titles:
      - "Volunteer"
  - name: "Attendee"
    color: "3, 150, 254"
    background-size: 220
    ticket-titles:
      - "None"
data:
  - field: "First Name"
    font: "fonts/OpenSans-Bold.ttf"
    size: 140
    position: "100,500"
    color: "207,19,19"
    style: "capitals"
  - field: "Last Name"
    font: "fonts/OpenSans-Bold.ttf"
    size: 80
    position: "100,700"
    color: "0,0,0"
  - field: "Title"
    font:  "fonts/OpenSans-Regular.ttf"
    size: 70
    position: "100,930"
    color: "207,19,19"
  - field: "Company"
    font: "fonts/OpenSans-Semibold.ttf"
    size: 80
    position: "100,1020"
    color: "0,0,0"
fonts:
  - field: "attendee-type"
    font: "fonts/OpenSans-Bold.ttf"
    size: 140
    position: "270,1610"
    color: "255,255,255"
    style: "capitals"
pre-order-data-extend:
  - field: "Company/Organization"
    extends: "Company"
pre-order-data:
  - field: "Job Title"
    font: "fonts/OpenSans-Regular.ttf"
    size: 50
    style: "capitals"
    position: "100, 700"
    color: "207,19,19"
qr-code:
  status: "vcard"
  position: "800, 120"
